apiVersion: apps/v1
kind: Deployment
metadata:
  name: leaderboard-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: leaderboard-service

  template:
    metadata:
      labels:
        app: leaderboard-service

    spec:
      containers:
        - name: leaderboard-service
          image: ghcr.io/M-Ali-Fouladi/leaderboard-service:208b14fb7a67b15236c6560aee4e4a03f9596e96
          imagePullPolicy: Always

          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: leaderboard-service

spec:
  selector:
    app: leaderboard-service

  ports:
    - port: 80
      targetPort: 8000

  type: ClusterIP