apiVersion: apps/v1
kind: Deployment
metadata:
  name: leaderboard-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: leaderboard-service

  template:
    metadata:
      labels:
        app: leaderboard-service

    spec:
      containers:
        - name: leaderboard-service
          image: ghcr.io/M-Ali-Fouladi/leaderboard-service:bf6880c1f4e0b48b8a4af32bd11ab5364f94a994
          imagePullPolicy: Always

          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: leaderboard-service

spec:
  selector:
    app: leaderboard-service

  ports:
    - port: 80
      targetPort: 8000

  type: ClusterIP