apiVersion: apps/v1
kind: Deployment
metadata:
  name: matchmaking-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: matchmaking-service

  template:
    metadata:
      labels:
        app: matchmaking-service

    spec:
      containers:
        - name: matchmaking-service
          image: ghcr.io/M-Ali-Fouladi/matchmaking-service:65d27d358f86d89a320c7fd769e3eb0d58a5f0af
          imagePullPolicy: Always

          ports:
            - containerPort: 8000

          env:
          
            - name: REDIS_URL
              value: "redis://redis:6379"

---
apiVersion: v1
kind: Service
metadata:
  name: matchmaking-service

spec:
  selector:
    app: matchmaking-service

  ports:
    - port: 80
      targetPort: 8000

  type: ClusterIP