apiVersion: apps/v1
kind: Deployment
metadata:
  name: player-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: player-service

  template:
    metadata:
      labels:
        app: player-service

    spec:
      containers:
        - name: player-service
          image: ghcr.io/M-Ali-Fouladi/player-service:5b6689f3e0ca50d200e553b1dd0c420b1ceaabab
          imagePullPolicy: Always

          ports:
            - containerPort: 8000

          env:
            - name: DATABASE_URL
              value: "postgresql://game:gamepass@postgres:5432/game_db"

            - name: REDIS_URL
              value: "redis://redis:6379"

---
apiVersion: v1
kind: Service
metadata:
  name: player-service

spec:
  selector:
    app: player-service

  ports:
    - port: 80
      targetPort: 8000

  type: ClusterIP