apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: telemetry-service

  template:
    metadata:
      labels:
        app: telemetry-service

    spec:
      containers:
        - name: telemetry-service
          image: ghcr.io/M-Ali-Fouladi/telemetry-service:2a77180a27bb61138571ab3899d99405e57b0d9f
          imagePullPolicy: Always

          ports:
            - containerPort: 8000

          env:
              
            - name: REDIS_HOST 
              value: "redis" 
              
            - name: REDIS_PORT 
              value: "6379"

---
apiVersion: v1
kind: Service
metadata:
  name: telemetry-service

spec:
  selector:
    app: telemetry-service

  ports:
    - port: 80
      targetPort: 8000

  type: ClusterIP