apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: websocket-service

  template:
    metadata:
      labels:
        app: websocket-service

    spec:
      containers:
        - name: websocket-service
          image: ghcr.io/M-Ali-Fouladi/websocket-service:9306bd004c9497bacc7b7e1b227612dee151bc4a
          imagePullPolicy: Always

          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: websocket-service

spec:
  selector:
    app: websocket-service

  ports:
    - port: 80
      targetPort: 8000

  type: ClusterIP